// Mocks generated by Mockito 5.4.6 from annotations
// in sunnova_app/test/data/datasources/course/course_local_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;
import 'package:sunnova_app/core/services/database_helper.dart' as _i3;
import 'package:sunnova_app/data/models/assessment_question_model.dart' as _i11;
import 'package:sunnova_app/data/models/badge_model.dart' as _i8;
import 'package:sunnova_app/data/models/content_lesson_model.dart' as _i18;
import 'package:sunnova_app/data/models/course_module_model.dart' as _i16;
import 'package:sunnova_app/data/models/daily_worship_model.dart' as _i19;
import 'package:sunnova_app/data/models/item_shop_model.dart' as _i14;
import 'package:sunnova_app/data/models/leaderboard_rank_model.dart' as _i10;
import 'package:sunnova_app/data/models/lesson_unit_model.dart' as _i17;
import 'package:sunnova_app/data/models/question_hint_model.dart' as _i13;
import 'package:sunnova_app/data/models/user_achievement_model.dart' as _i9;
import 'package:sunnova_app/data/models/user_answer_log_model.dart' as _i12;
import 'package:sunnova_app/data/models/user_game_stats_model.dart' as _i6;
import 'package:sunnova_app/data/models/user_inventory_model.dart' as _i15;
import 'package:sunnova_app/data/models/user_lesson_progress_model.dart' as _i7;
import 'package:sunnova_app/data/models/user_profile_model.dart' as _i5;
import 'package:sunnova_app/data/models/user_worship_log_model.dart' as _i20;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i3.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<int> insertOrUpdate(
    String? tableName,
    Map<String, dynamic>? data,
    String? primaryKeyColumn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertOrUpdate, [
              tableName,
              data,
              primaryKeyColumn,
            ]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<Map<String, dynamic>?> getById(
    String? tableName,
    String? primaryKeyColumn,
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [tableName, primaryKeyColumn, id]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<int> deleteById(
    String? tableName,
    String? primaryKeyColumn,
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteById, [tableName, primaryKeyColumn, id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> cacheUserProfile(_i5.UserProfileModel? userProfile) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUserProfile, [userProfile]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.UserProfileModel?> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i4.Future<_i5.UserProfileModel?>.value(),
          )
          as _i4.Future<_i5.UserProfileModel?>);

  @override
  _i4.Future<void> clearUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserProfile, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheUserGameStats(_i6.UserGameStatsModel? stats) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUserGameStats, [stats]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.UserGameStatsModel?> getUserGameStats(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserGameStats, [userId]),
            returnValue: _i4.Future<_i6.UserGameStatsModel?>.value(),
          )
          as _i4.Future<_i6.UserGameStatsModel?>);

  @override
  _i4.Future<void> clearUserGameStats(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearUserGameStats, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheUserLessonProgress(
    List<_i7.UserLessonProgressModel>? progressList,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUserLessonProgress, [progressList]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.UserLessonProgressModel>> getUserLessonProgress(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserLessonProgress, [userId]),
            returnValue: _i4.Future<List<_i7.UserLessonProgressModel>>.value(
              <_i7.UserLessonProgressModel>[],
            ),
          )
          as _i4.Future<List<_i7.UserLessonProgressModel>>);

  @override
  _i4.Future<void> clearUserLessonProgress(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearUserLessonProgress, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheBadges(List<_i8.BadgeModel>? badges) =>
      (super.noSuchMethod(
            Invocation.method(#cacheBadges, [badges]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.BadgeModel>> getBadges() =>
      (super.noSuchMethod(
            Invocation.method(#getBadges, []),
            returnValue: _i4.Future<List<_i8.BadgeModel>>.value(
              <_i8.BadgeModel>[],
            ),
          )
          as _i4.Future<List<_i8.BadgeModel>>);

  @override
  _i4.Future<void> clearBadges() =>
      (super.noSuchMethod(
            Invocation.method(#clearBadges, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheUserAchievements(
    List<_i9.UserAchievementModel>? achievements,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUserAchievements, [achievements]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.UserAchievementModel>> getUserAchievements(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserAchievements, [userId]),
            returnValue: _i4.Future<List<_i9.UserAchievementModel>>.value(
              <_i9.UserAchievementModel>[],
            ),
          )
          as _i4.Future<List<_i9.UserAchievementModel>>);

  @override
  _i4.Future<void> clearUserAchievements(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearUserAchievements, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheLeaderboardRanks(
    List<_i10.LeaderboardRankModel>? ranks,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheLeaderboardRanks, [ranks]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i10.LeaderboardRankModel>> getLeaderboardRanks(
    String? rankType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLeaderboardRanks, [rankType]),
            returnValue: _i4.Future<List<_i10.LeaderboardRankModel>>.value(
              <_i10.LeaderboardRankModel>[],
            ),
          )
          as _i4.Future<List<_i10.LeaderboardRankModel>>);

  @override
  _i4.Future<void> clearLeaderboardRanks(String? rankType) =>
      (super.noSuchMethod(
            Invocation.method(#clearLeaderboardRanks, [rankType]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheAssessmentQuestions(
    List<_i11.AssessmentQuestionModel>? questions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheAssessmentQuestions, [questions]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i11.AssessmentQuestionModel>> getAssessmentQuestions(
    String? lessonId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAssessmentQuestions, [lessonId]),
            returnValue: _i4.Future<List<_i11.AssessmentQuestionModel>>.value(
              <_i11.AssessmentQuestionModel>[],
            ),
          )
          as _i4.Future<List<_i11.AssessmentQuestionModel>>);

  @override
  _i4.Future<void> clearAssessmentQuestions(String? lessonId) =>
      (super.noSuchMethod(
            Invocation.method(#clearAssessmentQuestions, [lessonId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheUserAnswerLog(_i12.UserAnswerLogModel? answerLog) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUserAnswerLog, [answerLog]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i12.UserAnswerLogModel?> getUserAnswerLog(
    String? userId,
    String? questionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserAnswerLog, [userId, questionId]),
            returnValue: _i4.Future<_i12.UserAnswerLogModel?>.value(),
          )
          as _i4.Future<_i12.UserAnswerLogModel?>);

  @override
  _i4.Future<void> clearUserAnswerLog(String? userId, String? questionId) =>
      (super.noSuchMethod(
            Invocation.method(#clearUserAnswerLog, [userId, questionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheQuestionHint(_i13.QuestionHintModel? hint) =>
      (super.noSuchMethod(
            Invocation.method(#cacheQuestionHint, [hint]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i13.QuestionHintModel?> getQuestionHint(String? questionId) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionHint, [questionId]),
            returnValue: _i4.Future<_i13.QuestionHintModel?>.value(),
          )
          as _i4.Future<_i13.QuestionHintModel?>);

  @override
  _i4.Future<void> clearQuestionHint(String? questionId) =>
      (super.noSuchMethod(
            Invocation.method(#clearQuestionHint, [questionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheItemShopEntities(List<_i14.ItemShopModel>? items) =>
      (super.noSuchMethod(
            Invocation.method(#cacheItemShopEntities, [items]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i14.ItemShopModel>> getItemShopEntities() =>
      (super.noSuchMethod(
            Invocation.method(#getItemShopEntities, []),
            returnValue: _i4.Future<List<_i14.ItemShopModel>>.value(
              <_i14.ItemShopModel>[],
            ),
          )
          as _i4.Future<List<_i14.ItemShopModel>>);

  @override
  _i4.Future<void> clearItemShopEntities() =>
      (super.noSuchMethod(
            Invocation.method(#clearItemShopEntities, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheUserInventory(
    List<_i15.UserInventoryModel>? inventory,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUserInventory, [inventory]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i15.UserInventoryModel>> getUserInventory(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserInventory, [userId]),
            returnValue: _i4.Future<List<_i15.UserInventoryModel>>.value(
              <_i15.UserInventoryModel>[],
            ),
          )
          as _i4.Future<List<_i15.UserInventoryModel>>);

  @override
  _i4.Future<void> clearUserInventory(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearUserInventory, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheCourseModules(List<_i16.CourseModuleModel>? modules) =>
      (super.noSuchMethod(
            Invocation.method(#cacheCourseModules, [modules]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i16.CourseModuleModel>> getCourseModules() =>
      (super.noSuchMethod(
            Invocation.method(#getCourseModules, []),
            returnValue: _i4.Future<List<_i16.CourseModuleModel>>.value(
              <_i16.CourseModuleModel>[],
            ),
          )
          as _i4.Future<List<_i16.CourseModuleModel>>);

  @override
  _i4.Future<void> clearCourseModules() =>
      (super.noSuchMethod(
            Invocation.method(#clearCourseModules, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheLessonUnits(List<_i17.LessonUnitModel>? units) =>
      (super.noSuchMethod(
            Invocation.method(#cacheLessonUnits, [units]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i17.LessonUnitModel>> getLessonUnits(String? moduleId) =>
      (super.noSuchMethod(
            Invocation.method(#getLessonUnits, [moduleId]),
            returnValue: _i4.Future<List<_i17.LessonUnitModel>>.value(
              <_i17.LessonUnitModel>[],
            ),
          )
          as _i4.Future<List<_i17.LessonUnitModel>>);

  @override
  _i4.Future<void> clearLessonUnits(String? moduleId) =>
      (super.noSuchMethod(
            Invocation.method(#clearLessonUnits, [moduleId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheContentLessons(
    List<_i18.ContentLessonModel>? lessons,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheContentLessons, [lessons]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i18.ContentLessonModel>> getContentLessons(String? unitId) =>
      (super.noSuchMethod(
            Invocation.method(#getContentLessons, [unitId]),
            returnValue: _i4.Future<List<_i18.ContentLessonModel>>.value(
              <_i18.ContentLessonModel>[],
            ),
          )
          as _i4.Future<List<_i18.ContentLessonModel>>);

  @override
  _i4.Future<void> clearContentLessons(String? unitId) =>
      (super.noSuchMethod(
            Invocation.method(#clearContentLessons, [unitId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheDailyWorshipActivities(
    List<_i19.DailyWorshipModel>? activities,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheDailyWorshipActivities, [activities]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i19.DailyWorshipModel>> getDailyWorshipActivities() =>
      (super.noSuchMethod(
            Invocation.method(#getDailyWorshipActivities, []),
            returnValue: _i4.Future<List<_i19.DailyWorshipModel>>.value(
              <_i19.DailyWorshipModel>[],
            ),
          )
          as _i4.Future<List<_i19.DailyWorshipModel>>);

  @override
  _i4.Future<void> clearDailyWorshipActivities() =>
      (super.noSuchMethod(
            Invocation.method(#clearDailyWorshipActivities, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheUserWorshipLogs(List<_i20.UserWorshipLogModel>? logs) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUserWorshipLogs, [logs]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i20.UserWorshipLogModel>> getUserWorshipLogs(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserWorshipLogs, [userId, date]),
            returnValue: _i4.Future<List<_i20.UserWorshipLogModel>>.value(
              <_i20.UserWorshipLogModel>[],
            ),
          )
          as _i4.Future<List<_i20.UserWorshipLogModel>>);

  @override
  _i4.Future<void> clearUserWorshipLogs(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearUserWorshipLogs, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
