// Mocks generated by Mockito 5.4.6 from annotations
// in sunnova_app/test/data/repositories/daily_activity/daily_activity_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sunnova_app/data/datasources/daily_activity/daily_activity_local_data_source.dart'
    as _i6;
import 'package:sunnova_app/data/datasources/daily_activity/daily_activity_remote_data_source.dart'
    as _i2;
import 'package:sunnova_app/data/models/daily_worship_model.dart' as _i4;
import 'package:sunnova_app/data/models/user_worship_log_model.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DailyActivityRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDailyActivityRemoteDataSource extends _i1.Mock
    implements _i2.DailyActivityRemoteDataSource {
  MockDailyActivityRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.DailyWorshipModel>> getDailyWorships() =>
      (super.noSuchMethod(
            Invocation.method(#getDailyWorships, []),
            returnValue: _i3.Future<List<_i4.DailyWorshipModel>>.value(
              <_i4.DailyWorshipModel>[],
            ),
          )
          as _i3.Future<List<_i4.DailyWorshipModel>>);

  @override
  _i3.Future<void> logUserWorship(_i5.UserWorshipLogModel? worshipLog) =>
      (super.noSuchMethod(
            Invocation.method(#logUserWorship, [worshipLog]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.UserWorshipLogModel>> getUserWorshipLogs(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserWorshipLogs, [userId, date]),
            returnValue: _i3.Future<List<_i5.UserWorshipLogModel>>.value(
              <_i5.UserWorshipLogModel>[],
            ),
          )
          as _i3.Future<List<_i5.UserWorshipLogModel>>);
}

/// A class which mocks [DailyActivityLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDailyActivityLocalDataSource extends _i1.Mock
    implements _i6.DailyActivityLocalDataSource {
  MockDailyActivityLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> cacheDailyWorshipActivities(
    List<_i4.DailyWorshipModel>? activities,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheDailyWorshipActivities, [activities]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cacheUserWorshipLogs(List<_i5.UserWorshipLogModel>? logs) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUserWorshipLogs, [logs]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearDailyWorshipActivities() =>
      (super.noSuchMethod(
            Invocation.method(#clearDailyWorshipActivities, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearUserWorshipLogs(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearUserWorshipLogs, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.DailyWorshipModel>> getLastDailyWorshipActivities() =>
      (super.noSuchMethod(
            Invocation.method(#getLastDailyWorshipActivities, []),
            returnValue: _i3.Future<List<_i4.DailyWorshipModel>>.value(
              <_i4.DailyWorshipModel>[],
            ),
          )
          as _i3.Future<List<_i4.DailyWorshipModel>>);

  @override
  _i3.Future<List<_i5.UserWorshipLogModel>> getLastUserWorshipLogs(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLastUserWorshipLogs, [userId, date]),
            returnValue: _i3.Future<List<_i5.UserWorshipLogModel>>.value(
              <_i5.UserWorshipLogModel>[],
            ),
          )
          as _i3.Future<List<_i5.UserWorshipLogModel>>);
}
