// Mocks generated by Mockito 5.4.6 from annotations
// in sunnova_app/test/data/repositories/course/course_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sunnova_app/data/datasources/course/course_local_data_source.dart'
    as _i7;
import 'package:sunnova_app/data/datasources/course/course_remote_data_source.dart'
    as _i2;
import 'package:sunnova_app/data/models/content_lesson_model.dart' as _i6;
import 'package:sunnova_app/data/models/course_module_model.dart' as _i4;
import 'package:sunnova_app/data/models/lesson_unit_model.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CourseRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseRemoteDataSource extends _i1.Mock
    implements _i2.CourseRemoteDataSource {
  MockCourseRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CourseModuleModel>> getCourseModules() =>
      (super.noSuchMethod(
            Invocation.method(#getCourseModules, []),
            returnValue: _i3.Future<List<_i4.CourseModuleModel>>.value(
              <_i4.CourseModuleModel>[],
            ),
          )
          as _i3.Future<List<_i4.CourseModuleModel>>);

  @override
  _i3.Future<List<_i5.LessonUnitModel>> getLessonUnits(String? moduleId) =>
      (super.noSuchMethod(
            Invocation.method(#getLessonUnits, [moduleId]),
            returnValue: _i3.Future<List<_i5.LessonUnitModel>>.value(
              <_i5.LessonUnitModel>[],
            ),
          )
          as _i3.Future<List<_i5.LessonUnitModel>>);

  @override
  _i3.Future<List<_i6.ContentLessonModel>> getContentLessons(String? unitId) =>
      (super.noSuchMethod(
            Invocation.method(#getContentLessons, [unitId]),
            returnValue: _i3.Future<List<_i6.ContentLessonModel>>.value(
              <_i6.ContentLessonModel>[],
            ),
          )
          as _i3.Future<List<_i6.ContentLessonModel>>);
}

/// A class which mocks [CourseLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseLocalDataSource extends _i1.Mock
    implements _i7.CourseLocalDataSource {
  MockCourseLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CourseModuleModel>> getLastCourseModules() =>
      (super.noSuchMethod(
            Invocation.method(#getLastCourseModules, []),
            returnValue: _i3.Future<List<_i4.CourseModuleModel>>.value(
              <_i4.CourseModuleModel>[],
            ),
          )
          as _i3.Future<List<_i4.CourseModuleModel>>);

  @override
  _i3.Future<void> cacheCourseModules(List<_i4.CourseModuleModel>? modules) =>
      (super.noSuchMethod(
            Invocation.method(#cacheCourseModules, [modules]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearCourseModules() =>
      (super.noSuchMethod(
            Invocation.method(#clearCourseModules, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.LessonUnitModel>> getLastLessonUnits(String? moduleId) =>
      (super.noSuchMethod(
            Invocation.method(#getLastLessonUnits, [moduleId]),
            returnValue: _i3.Future<List<_i5.LessonUnitModel>>.value(
              <_i5.LessonUnitModel>[],
            ),
          )
          as _i3.Future<List<_i5.LessonUnitModel>>);

  @override
  _i3.Future<void> cacheLessonUnits(List<_i5.LessonUnitModel>? units) =>
      (super.noSuchMethod(
            Invocation.method(#cacheLessonUnits, [units]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearLessonUnits(String? moduleId) =>
      (super.noSuchMethod(
            Invocation.method(#clearLessonUnits, [moduleId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.ContentLessonModel>> getLastContentLessons(
    String? unitId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLastContentLessons, [unitId]),
            returnValue: _i3.Future<List<_i6.ContentLessonModel>>.value(
              <_i6.ContentLessonModel>[],
            ),
          )
          as _i3.Future<List<_i6.ContentLessonModel>>);

  @override
  _i3.Future<void> cacheContentLessons(List<_i6.ContentLessonModel>? lessons) =>
      (super.noSuchMethod(
            Invocation.method(#cacheContentLessons, [lessons]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearContentLessons(String? unitId) =>
      (super.noSuchMethod(
            Invocation.method(#clearContentLessons, [unitId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
